on:
  pull_request:

name: Static Linting
jobs:
  mypy-checker:
    name: Mypy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install Ubuntu dependencies
        run: |
          sudo apt update
          sudo apt install python3-yaml python3-requests python3-pil python3-gi python3-gi-cairo \
            gir1.2-gtk-3.0 gir1.2-gnomedesktop-3.0 gir1.2-webkit2-4.0 \
            gir1.2-notify-0.7 psmisc cabextract unzip p7zip curl fluid-soundfont-gs \
            x11-xserver-utils python3-evdev libgirepository1.0-dev \
            python3-setproctitle python3-distro
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy
          mypy --install-types --non-interactive
      - name: Run mypy analysis
        run: |
          mypy --version
          mypy . --strict
